[[segments]]
name = "lighting_stub"
index = 0
inputs = ["Texture2D:gbuffer_albedo", "Texture2D:gbuffer_normal", "DepthTexture:gbuffer_depth", "DepthTexture:shadow_map"]
outputs = ["Texture2D:lit_color"]
fragment = "shaders/showcase/common/pass.fsh"
