[[segments]]
name = "shadow_stub"
index = 0
inputs = ["Buffer:scene_geometry", "Buffer:light_params"]
outputs = ["DepthTexture:shadow_map"]
vertex = "shaders/showcase/common/fullscreen.vsh"
fragment = "shaders/showcase/common/pass.fsh"
